from __future__ import annotations
import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
#!/usr/bin/env python
"""
Standalone verification for Phase 2 Step 1 (Smart Consumer Router & Batching).

Run: python scripts/phase2_test_step1_consumer.py
"""


from unittest.mock import MagicMock

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
API_DIR = ROOT_DIR / "api"

if "kafka" not in sys.modules:
    kafka_stub = MagicMock()
    kafka_stub.KafkaConsumer = MagicMock()
    sys.modules["kafka"] = kafka_stub

if "pymongo" not in sys.modules:
    pymongo_stub = MagicMock()
    pymongo_stub.MongoClient = MagicMock()
    sys.modules["pymongo"] = pymongo_stub

if str(API_DIR) not in sys.path:
    sys.path.insert(0, str(API_DIR))

from app.consumer import SmartRouter  # noqa: E402


def build_mock_db():
    collections = {
        "corporate_run_logs": MagicMock(),
        "corporate_select_logs": MagicMock(),
        "correction_history": MagicMock(),
        "log_a_recommend": MagicMock(),
        "log_b_run": MagicMock(),
        "log_c_select": MagicMock(),
        "log_i_meta": MagicMock(),
        "full_document_store": MagicMock(),
    }

    class DummyDB(dict):
        def __getitem__(self, item):
            return collections[item]

    db = DummyDB(collections)
    mongo_client = MagicMock()
    mongo_client.__getitem__.return_value = db
    return mongo_client, collections


def run_tests() -> None:
    mongo_client, collections = build_mock_db()
    router = SmartRouter(mongo_client=mongo_client, batch_size=2, flush_interval=3600)

    run_event = {
        "event": "editor_run_paraphrasing",
        "insert_id": "run-1",
        "time": 111,
        "distinct_id": "user-1",
        "llm_name": "gemini",
        "maintenance": "moderate",
    }
    router.handle_payload(run_event)

    select_event = {
        "event": "editor_selected_paraphrasing",
        "insert_id": "sel-1",
        "time": 222,
        "distinct_id": "user-1",
        "index": 0,
        "selected_sentence_id": "sent-1",
        "maintenance": "strong",
        "field": "email",
        "target_language": "ko",
        "user_prompt": "Make it polite",
        "selected_text": "Hello",
        "paraphrasing_candidates": ["Hi", "Greetings"],
        "was_accepted": True,
    }
    router.handle_payload(select_event)

    router.flush_all()

    assert collections["corporate_run_logs"].insert_many.called, "Run logs not persisted"
    assert collections["log_b_run"].insert_many.called, "LogB missing"
    assert collections["corporate_select_logs"].insert_many.called, "Select logs not persisted"
    assert collections["log_c_select"].insert_many.called, "LogC missing"
    assert collections["correction_history"].insert_many.called, "Correction history not persisted"

    print("✅ Phase 2 Step 1 Smart Consumer Test Passed")


if __name__ == "__main__":
    run_tests()

