import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
import sys
import os
import asyncio
from pathlib import Path
from datetime import datetime
import numpy as np
from pymongo import MongoClient

# --- Path Setup ---
BASE_DIR = Path(__file__).resolve().parents[1]  # /app
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

# Import service
try:
    from app.services.profile_service import ProfileService
except ImportError as e:
    print(f"[ERROR] Failed to import ProfileService: {e}")
    sys.exit(1)

# --- Constants ---
MONGO_URI = os.getenv("MONGO_URI", "mongodb://mongo:27017")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "sentencify")
TEST_USER_ID = "test-user-profile-001"

# --- Mock Data Generation ---
def generate_mock_data():
    """
    Generates 5 sessions for the test user:
    - 3 Accepted (email, email, report)
    - 2 Rejected
    """
    data = {
        "log_a": [],
        "training": []
    }
    
    # 3 Accepted
    for i in range(3):
        sess_id = f"sess-acc-{i}"
        # Log A (Link user to session)
        data["log_a"].append({
            "recommend_session_id": sess_id,
            "user_id": TEST_USER_ID,
            "created_at": datetime.utcnow()
        })
        # Training Example
        data["training"].append({
            "example_id": sess_id,
            "recommend_session_id": sess_id,
            "was_accepted": True,
            "groundtruth_field": "email" if i < 2 else "report", # 2 emails, 1 report
            "tone": "formal",
            "context_embedding": [0.1 * (i+1)] * 3 # [0.1, 0.1, 0.1], [0.2...], [0.3...]
        })
        
    # 2 Rejected
    for i in range(3, 5):
        sess_id = f"sess-rej-{i}"
        data["log_a"].append({
            "recommend_session_id": sess_id,
            "user_id": TEST_USER_ID,
            "created_at": datetime.utcnow()
        })
        data["training"].append({
            "example_id": sess_id,
            "recommend_session_id": sess_id,
            "was_accepted": False,
            "context_embedding": [0.5] * 3
        })
        
    return data

# --- Test Logic ---
def run_tests():
    print("\n>>> Starting User Profile Service Test (Step 3)...")
    
    client = MongoClient(MONGO_URI)
    db = client[MONGO_DB_NAME]
    
    try:
        # 1. Cleanup
        db["log_a_recommend"].delete_many({"user_id": TEST_USER_ID})
        db["training_examples"].delete_many({"recommend_session_id": {"$regex": "^sess-(acc|rej)-"}})
        db["users"].delete_many({"user_id": TEST_USER_ID})
        print("🧼 Cleaned up test data.")

        # 2. Inject Data
        mock_data = generate_mock_data()
        db["log_a_recommend"].insert_many(mock_data["log_a"])
        db["training_examples"].insert_many(mock_data["training"])
        print(f"💉 Injected {len(mock_data['training'])} training examples.")
        
        # 3. Run Service
        print("🚀 Running ProfileService...")
        service = ProfileService(mongo_client=client)
        profile = service.update_user_profile(TEST_USER_ID)
        
        # 4. Verification
        print("🔍 Verifying User Profile...")
        if not profile:
            print("❌ Error: Profile was not returned.")
            sys.exit(1)
            
        print(f"   - User ID: {profile.user_id}")
        print(f"   - Accept Rate: {profile.recommend_accept_rate}")
        print(f"   - Embedding V1: {profile.user_embedding_v1}")
        print(f"   - Categories: {profile.preferred_category_vector}")
        
        # Check Accept Rate: 3/5 = 0.6
        assert abs(profile.recommend_accept_rate - 0.6) < 0.001, f"Expected 0.6, got {profile.recommend_accept_rate}"
        
        # Check Embedding: Mean of [0.1], [0.2], [0.3], [0.5], [0.5] -> Mean = 0.32
        # Note: All 5 examples have embeddings.
        expected_mean = np.mean([0.1, 0.2, 0.3, 0.5, 0.5]) # 0.32
        assert abs(profile.user_embedding_v1[0] - expected_mean) < 0.001, f"Expected mean {expected_mean}, got {profile.user_embedding_v1[0]}"
        
        # Check Category Vector (based on our fixed list in service: email, report, message, wiki)
        # Accepted only: 2 emails, 1 report. Total 3.
        # email: 2/3 = 0.666, report: 1/3 = 0.333
        # Indices: email=0, report=1
        assert abs(profile.preferred_category_vector[0] - 0.666) < 0.01, "Email category preference mismatch"
        assert abs(profile.preferred_category_vector[1] - 0.333) < 0.01, "Report category preference mismatch"

        print("\n✅ Phase 2 Step 3 User Profile Service Test Passed")

    except Exception as e:
        print(f"\n❌ Test failed with exception: {e}")
        # import traceback
        # traceback.print_exc()
        sys.exit(1)
    finally:
        client.close()

if __name__ == "__main__":
    run_tests()
