from __future__ import annotations
import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
#!/usr/bin/env python
"""
Standalone verification script for Phase 1.5 Step 1 (Redis + Schema F).

Run: python scripts/test_step1_redis.py
"""


import asyncio
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

from redis.exceptions import ConnectionError as RedisConnectionError

ROOT_DIR = Path(__file__).resolve().parents[1]
API_DIR = ROOT_DIR / "api"

if str(API_DIR) not in sys.path:
    sys.path.insert(0, str(API_DIR))

from app.redis.client import (  # noqa: E402
    get_macro_context,
    get_redis_client,
    set_macro_context,
)
from app.schemas.macro import DocumentContextCache  # noqa: E402


async def main() -> None:
    host = os.getenv("REDIS_HOST", "redis")
    port = os.getenv("REDIS_PORT", "6379")
    print(f"[Redis] Connecting to {host}:{port}")
    client = get_redis_client()
    await client.ping()
    print("[Redis] Connection successful.")

    doc_id = f"doc-{uuid4()}"
    now = datetime.now(timezone.utc)

    cache_entry = DocumentContextCache(
        doc_id=doc_id,
        macro_topic="phase1.5.test",
        macro_category_hint="redis-check",
        macro_llm_version="macro-llm-v0",
        cache_hit_count=3,
        last_updated=now,
        valid_until=now + timedelta(minutes=15),
        invalidated_by_diff=False,
        diff_ratio=0.25,
    )

    await set_macro_context(doc_id, cache_entry, ttl=120)
    restored = await get_macro_context(doc_id)

    assert restored is not None, "Cache retrieval failed; no payload found."
    assert restored == cache_entry, "Retrieved payload does not match the saved Schema F object."

    print("✅ Step 1 Redis Test Passed")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except RedisConnectionError as exc:
        host = os.getenv("REDIS_HOST", "localhost")
        port = os.getenv("REDIS_PORT", "6379")
        print(f"[Redis] Connection failed to {host}:{port} -> {exc}")
        raise SystemExit(1)

