from __future__ import annotations
import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
#!/usr/bin/env python
"""
Standalone verification for Phase 2 Step 4 (Vector DB Migration).

Run: python scripts/phase2_test_step4_migration.py
"""


from unittest.mock import MagicMock

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
API_DIR = ROOT_DIR / "api"

if "pymongo" not in sys.modules:
    pymongo_stub = MagicMock()
    pymongo_stub.MongoClient = MagicMock()
    sys.modules["pymongo"] = pymongo_stub

if "qdrant_client" not in sys.modules:
    class DummyPointStruct:
        def __init__(self, id, vector, payload):
            self.id = id
            self.vector = vector
            self.payload = payload

    qdrant_stub = MagicMock()
    qdrant_stub.QdrantClient = MagicMock()
    qdrant_stub.models = MagicMock()
    qdrant_stub.models.PointStruct = DummyPointStruct
    sys.modules["qdrant_client"] = qdrant_stub
    sys.modules["qdrant_client.models"] = qdrant_stub.models

if str(API_DIR) not in sys.path:
    sys.path.insert(0, str(API_DIR))

from app.services.vector_migration import migrate_vectors_to_qdrant  # noqa: E402


def run_tests() -> None:
    mock_cursor = [
        {
            "example_id": "ex-1",
            "context_embedding": [0.1, 0.2, 0.3],
            "groundtruth_field": "email",
            "doc_id": "doc-1",
            "user_id": "user-1",
            "created_at": "2025-01-01T00:00:00Z",
            "consistency_flag": "high",
            "was_accepted": True,
        },
        {
            "example_id": "ex-2",
            "context_embedding": [0.4, 0.5, 0.6],
            "groundtruth_field": None,
        },
    ]

    training_collection = MagicMock()
    training_collection.find.return_value = mock_cursor

    class DummyDB:
        def __init__(self, collections):
            self.collections = collections

        def __getitem__(self, key):
            return self.collections[key]

    mongo_client = MagicMock()
    mongo_client.__getitem__.return_value = DummyDB(
        {"training_examples": training_collection}
    )

    qdrant_client = MagicMock()

    migrated = migrate_vectors_to_qdrant(
        batch_size=10,
        mongo_client=mongo_client,
        qdrant_client=qdrant_client,
    )

    assert migrated == 2, "Migration count mismatch"
    assert qdrant_client.upsert.called, "Qdrant upsert not called"
    args, kwargs = qdrant_client.upsert.call_args
    assert kwargs["collection_name"] == "context_block_v1"
    points = kwargs["points"]
    payload = points[0].payload
    assert payload["field"] == "email"
    assert payload["source_type"] == "real_user"

    print("✅ Phase 2 Step 4 Vector Migration Test Passed")


if __name__ == "__main__":
    run_tests()

