import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
import sys
import os
import asyncio
from pathlib import Path
from datetime import datetime, timedelta
from typing import List, Dict, Any
from pymongo import MongoClient

# --- Path Setup ---
BASE_DIR = Path(__file__).resolve().parents[1]  # /app
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

# Import service function
try:
    from app.services.etl_service import run_etl_pipeline
except ImportError as e:
    print(f"[ERROR] Failed to import services: {e}")
    sys.exit(1)

# --- Constants ---
MONGO_URI = os.getenv("MONGO_URI", "mongodb://mongo:27017")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "sentencify")

# --- Mock Data ---
SESSION_ID = "test-session-etl-123"
A_INSERT_ID = "a-log-insert-id-456"
DOC_ID = "doc-abc-789"
CONTEXT_HASH = "hash-def-456"

# A: editor_recommend_options event
MOCK_LOG_A = {
    "insert_id": A_INSERT_ID,
    "recommend_session_id": SESSION_ID,
    "doc_id": DOC_ID,
    "context_hash": CONTEXT_HASH,
    "created_at": "2025-01-01T10:00:00Z",
    "reco_options": [{"category": "email", "language": "ko", "intensity": "moderate"}],
    "P_vec": {"email": 0.8, "report": 0.2},
    "P_doc": {"email": 0.6, "report": 0.4},
    "applied_weight_doc": 0.5,
    "doc_maturity_score": 0.75,
    "is_shadow_mode": False,
}

# B: editor_run_paraphrasing event
MOCK_LOG_B = {
    "source_recommend_event_id": A_INSERT_ID,
    "recommend_session_id": SESSION_ID,
    "doc_id": DOC_ID,
    "created_at": "2025-01-01T10:00:15Z",  # 15 seconds after A
    "target_category": "email",
    "tone": "formal",
    "llm_provider": "google",
    "response_time_ms": 250,
}

# C: editor_selected_paraphrasing event
MOCK_LOG_C = {
    "source_recommend_event_id": A_INSERT_ID,
    "recommend_session_id": SESSION_ID,
    "doc_id": DOC_ID,
    "field": "email",
    "was_accepted": True,
    "index": 1,
}

# D: correction_history
MOCK_LOG_D = {
    "recommend_session_id": SESSION_ID,
    "field": "email",
    "input_sentence": "original text",
    "output_sentences": ["candidate 1", "candidate 2"],
    "selected_index": 1
}

# --- Test Logic ---
def run_tests():
    print("\n>>> Starting ETL Pipeline Integration Test (Step 2)...")
    
    try:
        client = MongoClient(MONGO_URI)
        db = client[MONGO_DB_NAME]
        
        # 1. Cleanup previous test data
        collections_to_clean = [
            "log_a_recommend", "log_b_run", "log_c_select",
            "correction_history", "training_examples"
        ]
        for col in collections_to_clean:
            db[col].delete_many({"recommend_session_id": SESSION_ID}) # Clean only test data
        print("🧼 Cleaned up test data.")

        # 2. Inject mock data
        db["log_a_recommend"].insert_one(MOCK_LOG_A)
        db["log_b_run"].insert_one(MOCK_LOG_B)
        db["log_c_select"].insert_one(MOCK_LOG_C)
        db["correction_history"].insert_one(MOCK_LOG_D)
        print("💉 Injected mock data.")
        
        # 3. Run ETL pipeline
        print("🚀 Running ETL pipeline...")
        # Since run_etl_pipeline processes ALL data, we check if our count increases or if our specific ID exists.
        # Ideally, we should use a test DB, but here we check for existence of our record.
        run_etl_pipeline(mongo_client=client)
        
        # 4. Verification
        result = db["training_examples"].find_one({"example_id": SESSION_ID})
        
        if result:
            print("🔍 Verifying generated TrainingExample...")
            assert result["consistency_flag"] == "high", "Consistency flag should be 'high'"
            assert result["groundtruth_field"] == "email"
            assert result["was_accepted"] is True
            assert result["doc_id"] == DOC_ID
            # P_vec check (simple dict comparison might be tricky due to float precision but usually works for exact values)
            assert result["P_vec"]["email"] == 0.8
            assert result["tone"] == MOCK_LOG_B["tone"]
            assert result["selected_index"] == MOCK_LOG_C["index"]
            
            print("\n✅ Phase 2 Step 2 ETL Service Test Passed")
        else:
            print("\n❌ Test failed: TrainingExample was not created in the database.")
            sys.exit(1)

    except Exception as e:
        print(f"\n❌ Test failed with exception: {e}")
        sys.exit(1)
    finally:
        # Cleanup
        if 'client' in locals() and client:
            # Optional: Clean up test data again? Maybe keep for inspection.
            # db["log_a_recommend"].delete_many({"recommend_session_id": SESSION_ID})
            # ...
            client.close()

if __name__ == "__main__":
    run_tests()
