import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
import requests
import time
import json
import os
import uuid
from kafka import KafkaProducer
from datetime import datetime, timezone, timedelta

# --- Configuration ---
API_HOST = os.getenv("API_HOST", "http://api:8000")
ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST", "http://elasticsearch:9200")
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
TEST_TOPIC = "editor_recommend_options"
TEST_INDEX_PREFIX = "sentencify-logs-"

# Function to get current time in ISO format for Logstash's date filter
def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec='milliseconds') + 'Z'

# --- 1. API Call Test ---
def send_test_recommend_request(doc_id: str, user_id: str):
    print(f"\n--- Sending test /recommend API request to {API_HOST} ---")
    payload = {
        "doc_id": doc_id,
        "user_id": user_id,
        "selected_text": "This is a test sentence for ELK integration.",
        "context_prev": "Previous context.",
        "context_next": "Next context."
    }
    try:
        response = requests.post(f"{API_HOST}/recommend", json=payload, timeout=10)
        response.raise_for_status()
        result = response.json()
        print(f"✅ /recommend API call successful. Session ID: {result.get('recommend_session_id')}")
        return result
    except requests.exceptions.RequestException as e:
        print(f"❌ /recommend API call failed: {e}")
        return None

# --- 2. Elasticsearch Search Function ---
def search_elasticsearch(insert_id: str, max_retries: int = 20, delay: int = 1):
    print(f"\n--- Searching for insert_id '{insert_id}' in Elasticsearch ---")
    search_url = f"{ELASTICSEARCH_HOST}/{TEST_INDEX_PREFIX}*/_search"
    query = {
        "query": {
            "match": {
                "insert_id.keyword": insert_id
            }
        }
    }

    for i in range(max_retries):
        time.sleep(delay)
        try:
            response = requests.post(search_url, json=query, timeout=5)
            response.raise_for_status()
            search_results = response.json()
            if search_results['hits']['total']['value'] > 0:
                hit = search_results['hits']['hits'][0]['_source']
                print(f"✅ Document found in Elasticsearch after {i*delay} seconds.")
                print(f"   - Event: {hit.get('event')}")
                print(f"   - insert_id: {hit.get('insert_id')}")
                print(f"   - recommend_session_id: {hit.get('recommend_session_id')}")
                print(f"   - @timestamp: {hit.get('@timestamp')}")
                return hit
        except requests.exceptions.RequestException as e:
            print(f"   Search attempt {i+1} failed: {e}")
            pass # Keep retrying

    print(f"❌ Document with insert_id '{insert_id}' not found in Elasticsearch after {max_retries*delay} seconds.")
    return None

# --- Main Execution ---
if __name__ == "__main__":
    test_user_id = str(uuid.uuid4())
    test_doc_id = str(uuid.uuid4())

    # Step 1: Send API request
    api_result = send_test_recommend_request(test_doc_id, test_user_id)
    if not api_result:
        print("\n--- ELK Pipeline Integration Test: FAILED (API call) ---")
        exit(1)

    insert_id_from_api = api_result.get("insert_id")
    if not insert_id_from_api:
        print("❌ API response did not contain 'insert_id'.")
        print("\n--- ELK Pipeline Integration Test: FAILED (API response) ---")
        exit(1)

    # Step 2: Search for the document in Elasticsearch
    es_doc = search_elasticsearch(insert_id_from_api)
    if es_doc:
        print("\n--- ELK Pipeline Integration Test: All checks passed! ---")
    else:
        print("\n--- ELK Pipeline Integration Test: FAILED (ES search) ---")
        exit(1)

