import sys
import os
from pathlib import Path

# --- Path Setup (Auto-generated by migration) ---
# Define Project Root (Assuming this file is in tests/)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add 'api' to sys.path to allow 'from app...' imports
if str(PROJECT_ROOT / "api") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "api"))

# Add Project Root to sys.path to allow 'from dashboard...' or other root imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
# ------------------------------------------------
import requests
import time
import json
import os
import uuid
from kafka import KafkaProducer
from datetime import datetime, timezone, timedelta

# --- Configuration ---
ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST", "http://localhost:9200")
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TEST_TOPIC = "editor_recommend_options" # Logstash pipeline listens to this
TEST_INDEX_PREFIX = "sentencify-logs-"

# Function to get current time in ISO format for Logstash's date filter
def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec='milliseconds') + 'Z'

# --- 1. Elasticsearch Health Check ---
def test_elasticsearch_connection():
    print(f"\n--- Testing Elasticsearch Connection to {ELASTICSEARCH_HOST} ---")
    try:
        response = requests.get(ELASTICSEARCH_HOST, timeout=5)
        response.raise_for_status() # Raise an exception for HTTP errors
        info = response.json()
        print(f"✅ Elasticsearch is UP. Version: {info['version']['number']}")
        return True
    except requests.exceptions.ConnectionError:
        print(f"❌ Connection to Elasticsearch failed. Is it running at {ELASTICSEARCH_HOST}?")
    except requests.exceptions.RequestException as e:
        print(f"❌ Elasticsearch returned an error: {e}")
    return False

# --- 2. Logstash-Kafka-Elasticsearch Pipeline Test ---
def test_logstash_pipeline():
    print(f"\n--- Testing Logstash Pipeline (Kafka -> ES) ---")
    producer = None
    try:
        producer = KafkaProducer(
            bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
            value_serializer=lambda v: json.dumps(v, ensure_ascii=False).encode("utf-8")
        )

        test_message_id = str(uuid.uuid4())
        test_message = {
            "event": "test_event",
            "insert_id": test_message_id,
            "user_id": "test_user_elk",
            "doc_id": "test_doc_elk",
            "created_at": _now_iso(), # Logstash will use this for @timestamp
            "test_payload_key": "test_payload_value"
        }

        print(f"Sending test message to Kafka topic '{TEST_TOPIC}'...")
        future = producer.send(TEST_TOPIC, value=test_message)
        producer.flush() # Ensure all messages are sent
        future.get(timeout=10) # Wait for message to be sent
        print(f"Sent: {test_message}")

        # Wait for Logstash to process and index the message
        print("Waiting for Logstash to process and index the message (max 15 seconds)...")
        search_url = f"{ELASTICSEARCH_HOST}/{TEST_INDEX_PREFIX}*/_search"
        query = {
            "query": {
                "match": {
                    "insert_id.keyword": test_message_id
                }
            }
        }

        for _ in range(15): # Try for 15 seconds
            time.sleep(1)
            try:
                response = requests.post(search_url, json=query, timeout=5)
                response.raise_for_status()
                search_results = response.json()
                if search_results['hits']['total']['value'] > 0:
                    hit = search_results['hits']['hits'][0]['_source']
                    print(f"✅ Test message found in Elasticsearch:")
                    print(f"   - insert_id: {hit.get('insert_id')}")
                    print(f"   - @timestamp: {hit.get('@timestamp')}")
                    print(f"   - test_payload_key: {hit.get('test_payload_key')}")
                    return True
            except requests.exceptions.RequestException as e:
                # print(f"Search attempt failed: {e}") # Debugging
                pass # Continue retrying

        print(f"❌ Test message '{test_message_id}' not found in Elasticsearch after 15 seconds.")
        return False

    except Exception as e:
        print(f"❌ An error occurred during pipeline test: {e}")
        return False
    finally:
        if producer:
            producer.close()

# --- Main Execution ---
if __name__ == "__main__":
    es_ok = test_elasticsearch_connection()
    if es_ok:
        pipeline_ok = test_logstash_pipeline()
        if pipeline_ok:
            print("\n--- ELK Stack Unit Test: All checks passed! ---")
        else:
            print("\n--- ELK Stack Unit Test: Pipeline check FAILED ---")
    else:
        print("\n--- ELK Stack Unit Test: Elasticsearch connection FAILED ---")

